
version: '3.7'

networks:
  web-realese:
    driver: bridge

services:

  db:
    image: mysql
    restart: always
    ports:
      - 3306:3306
    networks:
      - web-realese
    environment:
      MYSQL_USER: sys_admin
      MYSQL_PASSWORD: sys_password
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_DATABASE: DBProject